language: cpp
sudo: required
cache:
  directories:
   - apache-rpc-9.zip
   - thrift-0.9.3.tar.gz
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - g++-4.9
    - libbz2-dev
    - libboost1.55-all-dev
    - cmake
    - libgtest-dev
    - libprotobuf-dev
    - protobuf-compiler
before_script:
 - sudo apt-get update -qq
 - sudo apt-get bootstrap -qq uuid-dev libgsasl7-dev
 - ./bootstrap-gtest.sh
 - ./bootstrap-zookeeper.sh
 - ./bootstrap-thrift.sh
script:
  - export CXX="g++-4.9"
  - bootstrap

