language: cpp
sudo: required
cache:
  directories:
   - apache-rpc-9.zip
   - thrift-0.9.3.tar.gz
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - g++-4.9
    - libbz2-dev
    - libgsasl7-dev
    - uuid-dev
    - libboost1.55-all-dev
    - cmake
    - libgtest-dev
    - libevent-dev
    - libssl1.0-dev
    - libprotobuf-dev
    - protobuf-compiler
script:
  - export CXX="g++-4.9"
  - ./bootstrap-travis
